/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface DeviceIdentifier {
  kind: string;
  id: string;
  mdn?: string;
}

export const deviceIdentifierSchema: Schema<DeviceIdentifier> = object({
  kind: ['kind', string()],
  id: ['id', string()],
  mdn: ['mdn', optional(string())],
});
