/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema, string } from '../schema';
import { DeviceIdentifier, deviceIdentifierSchema } from './deviceIdentifier';

export interface GetDeviceExperienceScoreBulkRequest {
  accountName: string;
  deviceListItem: DeviceIdentifier[];
}

export const getDeviceExperienceScoreBulkRequestSchema: Schema<GetDeviceExperienceScoreBulkRequest> = object(
  {
    accountName: ['accountName', string()],
    deviceListItem: [
      'deviceListItem',
      array(lazy(() => deviceIdentifierSchema)),
    ],
  }
);
