/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import { Coordinates, coordinatesSchema } from './coordinates';

export interface GetNetworkConditionsRequest {
  accountName: string;
  locationType: string;
  coordinates: Coordinates;
}

export const getNetworkConditionsRequestSchema: Schema<GetNetworkConditionsRequest> = object(
  {
    accountName: ['accountName', string()],
    locationType: ['locationType', string()],
    coordinates: ['coordinates', lazy(() => coordinatesSchema)],
  }
);
