/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { AddressItem, addressItemSchema } from './addressItem';

export interface Locations {
  addressList?: AddressItem[];
}

export const locationsSchema: Schema<Locations> = object({
  addressList: ['addressList', optional(array(lazy(() => addressItemSchema)))],
});
