/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface WNPRequestResponse {
  requestId?: string;
}

export const wNPRequestResponseSchema: Schema<WNPRequestResponse> = object({
  requestId: ['requestId', optional(string())],
});
